# Generated by Django 6.0.4 on 2026-04-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentusage",
            name="parts_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
